#! /bin/sh

version() {
	py $(where gitext.py) version
}

usage() {
	py $(where gitext.py) help
}

main() {
	if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

   py $(where gitext.py) $subcommand
}

main "$@"