#! /bin/sh

version() {
	py gitext.py version
}

usage() {
	py gitext.py help
}

main() {
	if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

   py gitext.py $subcommand
}

main "$@"